import Equipartition.Canonical
import Equipartition.Examples
import Equipartition.GibbsMeasure
import Equipartition.IntegrationByParts
import Equipartition.MainTheorem
import Equipartition.Multivariate
